---
- hosts: webservers
  remote_user: root
  become: yes
  # become_user: root
  
  tasks:
    - name: install java dependancy
      apt:
        name: default-jre
        update_cache: yes

    - name: ensure the jenkins apt repo key is installed
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key 
        state: present

    - name: ensure repo is correclty configured
      apt_repo: 
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/' 
        state: present

    - name: ensure jenkins is correctly installed
      apt: 
        name: jenkins 
        update_cache: yes

    - name: ensure jenkins is running
      service: 
        name: jenkins 
        state: started