Vagrant.configure(2) do |config|

  config.vm.network "forwarded_port", guest: 8080, host: 1234, protocol: "tcp"
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
